env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - PROJECT_NAME=bbimports
  - PROJECT_USER=incu6us

before:
  hooks:
    - go mod download

builds:
  - id: bbimports-amd64
    binary: bbimports
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

  - id: bbimports-darwin-amd64
    binary: bbimports
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

  - id: bbimports-windows-amd64
    binary: bbimports
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.Tag={{ .Tag }}" -X "main.Commit={{ .FullCommit }}" -X "main.SourceURL={{ .GitURL }}" -X "main.GoVersion={{ .Env.GO_VERSION }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  github:
    owner: incu6us
    name: bbimports

brews:
  - name: bbimports
    tap:
      owner: incu6us
      name: homebrew-tap
    url_template: "https://github.com/{{ .Env.PROJECT_USER }}/{{ .ProjectName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: incu6us
      email: vyacheslavpryimak@gmail.com
    folder: Formula
    homepage: "https://github.com/incu6us/bbimports"
    description: "Right imports sorting & code formatting tool"
    test: |
      system "#{bin}/goimports-reviser -version"
    install: |
      bin.install "goimports-reviser"

snapcrafts:
  - id: bbimports
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: MacOS
    publish: true
    summary: "Right imports sorting & code formatting tool"
    description: |
      Tool for Golang to sort goimports by 3 groups: std, general and project dependencies. Also, formatting for your code will be prepared(so, you don't need to use gofmt or goimports separately).
    grade: stable
    confinement: strict
    license: MIT
